### ISSUE TITLE
[STORM-2091] storm-kafka-client, NoSuchMethod on KafkaConsumer.subscribe 

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#5873]
<p>Hello,</p>

<p>I am currently using storm-kafka-client "1.0.2" with kafka-clients "0.10.0.1" and I am encountering the following stacktrace at runtime of my topology:</p>

<p>java.lang.NoSuchMethodError: org.apache.kafka.clients.consumer.KafkaConsumer.subscribe(Ljava/util/List;Lorg/apache/kafka/clients/consumer/ConsumerRebalanceListener;)V at org.apache.storm.kafka.spout.KafkaSpout.subscribeKafkaConsumer(KafkaSpout.java:350) at org.apache.storm.kafka.spout.KafkaSpout.activate(KafkaSpout.java:341) at org.apache.storm.daemon.executor$fn_<em>7885$fn</em><em>7900$fn</em><em>7931.invoke(executor.clj:640) at org.apache.storm.util$async_loop$fn</em>_625.invoke(util.clj:484) at clojure.lang.AFn.run(AFn.java:22) at java.lang.Thread.run(Thread.java:745)</p>

<p>So I checked the source code and Indeed the subscribe method takes a collection of topics in addition of the listener: <a href="https://github.com/apache/kafka/blob/0.10.0.1/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L795" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/kafka/blob/0.10.0.1/clients/src/main/java/org/apache/kafka/clients/consumer/KafkaConsumer.java#L795</a></p>

<p>I though version 1.0.2 of storm-kafka-clients should work with kafka 0.10.0.1, do you have any idea ? Thanks.</p>

---
<details><summary><i>Originally reported by <a title="Pierre Padrixe" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stannie42">stannie42</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2091" target="_blank">storm-kafka-client, NoSuchMethod on KafkaConsumer.subscribe </a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Major
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2016-09-13T11:02:50+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stannie42">stannie42</a>:</i>
<p>I've built version 1.1.0 which works fine with kafka 0.10.0.1, closed this issue.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stannie42" class="user-hover" rel="stannie42">Pierre Padrixe</a><br/>
If you can still reproduce this with Storm 1.0.2, let's reopen this and set Affects Version/s to 1.0.2 so that fix could be available to 1.0.3.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=stannie42">stannie42</a>:</i>
<p>storm-kafka-client 1.0.x only works for 0.9.x and I was using the version 0.10.0.1 of kafka which only works with the version 1.1.0 of storm-kafka-client. So no need to re-open this ticket.</p>

<p>This could be clarified by updating the documentation at this page :<br/>
<a href="http://storm.apache.org/releases/1.0.2/storm-kafka.html" class="external-link" target="_blank" rel="nofollow noopener">http://storm.apache.org/releases/1.0.2/storm-kafka.html</a><br/>
and to provide a matrix of compatibility storm-kafka-client vs kafka versions.</p>

<p>If you need any help, let me know,</p>

<p>Thanks,<br/>
Pierre.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=kabhwan">kabhwan</a>:</i>
<p>Yes I missed it. Thanks. READMEs are clearly stating this.</p>

<p><a href="https://github.com/apache/storm/tree/1.0.x-branch/external/storm-kafka-client" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/tree/1.0.x-branch/external/storm-kafka-client</a><br/>
<a href="https://github.com/apache/storm/tree/1.x-branch/external/storm-kafka-client" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/storm/tree/1.x-branch/external/storm-kafka-client</a></p>

<p>Btw, we need to expose README of storm-kafka-client as website as well. Only old storm-kafka is on website.</p>
