### ISSUE TITLE
[STORM-2875] Hadoop-auth dependency in storm-core results in exception

### ISSUE THREAD

**Issue by jira-importer** [apache/storm#6657]
<p>Storm-core 1.1.1 ships with hadoop-auth dependency for version 2.6.1 which results in exceptions while working with hadoop version 2.8.x and above due to changes in KerberosUtil class.</p>

<p>_java.lang.NoSuchMethodError: org.apache.hadoop.security.authentication.util.KerberosUtil.hasKerberosKeyTab(Ljavax/security/auth/Subject;)Z<br/>
	at org.apache.hadoop.security.UserGroupInformation.<init>(UserGroupInformation.java:715) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.hadoop.security.UserGroupInformation.loginUserFromSubject(UserGroupInformation.java:925) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.hadoop.security.UserGroupInformation.getLoginUser(UserGroupInformation.java:873) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.hadoop.security.UserGroupInformation.getCurrentUser(UserGroupInformation.java:740) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3472) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.hadoop.fs.FileSystem$Cache$Key.<init>(FileSystem.java:3462) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3304) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:476) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.storm.hdfs.bolt.HdfsBolt.doPrepare(HdfsBolt.java:106) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.storm.hdfs.bolt.AbstractHdfsBolt.prepare(AbstractHdfsBolt.java:124) ~<span class="error">&#91;stormjar.jar:?&#93;</span><br/>
	at org.apache.storm.daemon.executor$fn_<em>5030$fn</em>_5043.invoke(executor.clj:793) ~<span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at org.apache.storm.util$async_loop$fn__557.invoke(util.clj:482) <span class="error">&#91;storm-core-1.1.1.jar:1.1.1&#93;</span><br/>
	at clojure.lang.AFn.run(AFn.java:22) <span class="error">&#91;clojure-1.7.0.jar:?&#93;</span><br/>
	at java.lang.Thread.run(Thread.java:748) <span class="error">&#91;?:1.8.0_151&#93;</span>_</p>

---
<details><summary><i>Originally reported by <a title="Durgesh" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=durgesh-w">durgesh-w</a>, imported from: <a href="https://issues.apache.org/jira/browse/STORM-2875" target="_blank">Hadoop-auth dependency in storm-core results in exception</a></i></summary>
<i><ul>
<li><b>status</b>: Closed
<li><b>priority</b>: Blocker
<li><b>resolution</b>: Won't Fix
<li><b>resolved</b>: 2024-07-02T10:46:57+01:00
<li><b>imported</b>: 2025-01-24
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=rzo1">rzo1</a>:</i>
<p>Storm 1.x isn't maintained anymore. If the issue still applies for 2.6.x, feel free to re-open.</p>
